### ISSUE TITLE
Review 'services' package

### ISSUE THREAD

**Issue by eugenesmkn** [Washubrnfg85/GetATest-telegramBot-#5]
Take a look at all services in the package (except SessionManager).
They look empty, so it might be a good idea to get rid of them at all and use the repositories directly in the SessionManager.

**Comment by Washubrnfg85** [comment]
Sure, if it is not a crime from an architectural point of view. Could this have a bad effect on flexibility and maintenance in the future?
I think it would be right to leave the SessionService interface and implementation as they are.

P.S.: Did it. Looks good.
